#######################################################################################################
# Version: 1.1.4                                                                                      #
# By: Xyaafol                                                                                         #
# Commands:                                                                                           #
# /vmreload - Reloads the plugin with settings changed in this file. Requires OP.                     #
# /vmbook - Gives the player a book example of the book used for the book restriction. Requires OP.   #
#######################################################################################################

# begin: Time in ticks that villagers can be traded from (day starts at 1000 ticks). Set to 2000 by default.
# end: time in ticks that villagers can be traded until (night starts at 13000 ticks). Set to 8999 by default.
# alert: sends a message to the player if enabled to tell them that the villager is ony available during work hours.

Work:
  begin: 2000
  end: 8999


# alert: Sends an alert to the players when they interact with an unavailable villager.
# on: 0 for off, 1 for on.
# message: The alert that will be sent to the player if alert is on.

alert:
  on: 0
  message: "This villager is outside of it's work times"



# allVillagers: Value of 0 by default means that only villagers with trades containing restricted books are bound by Work begin and Work end.
#Set to 1 for all villagers to be restricted.

allVillagers: 0



# CustomItem: Add the bukkit name of any item here that villagers sell to alter its trade.
#Copy the example of clock at the bottom of the config in order to edit the changes to the trade.

CustomItem:
  - "CLOCK"
  - "COAL_ORE"



# enchantments: Enter any enchantments here and then their corresponding restrictions below
#Please ensure that all enchantments are spelt correctly and have the level following a colon after them
#Use underscores for all spaces in enchantment names
#Enchantments with no level normally attached to them should be written as 'silk_touch:1"

enchantments:
  - "mending:1"
  - "silk_touch:1"
  - "efficiency:5"
  - "efficiency:4"
  - "fortune:3"
  - "unbreaking:3"

# Book-Title: Controls the title of the book in the 'book' control for trades
# Book-Lore: Controls the lore of the book in the 'book' control for trades.
Book:
  Title: "Â§aVillager Trade Book"
  Lore: "Trade Value:1"

# mending: Copy this block of code and change the enchantment name to any that you would like to control.
#Use the same name as under enchantments but with the colon replaced with an underscore.

# restricted: Controls if villagers with this enchanted book follow the begin and end times above.
#Value of 0 by default for work time restrictions active on mending. Set to 0 for time restrictions off.

# change: Controls if villagers with this enchanted book have the trade containing said book changed to the following material, cost, book, and uses set below.
#Value of 0 by default, set to 1 to activate changed trades.

# material: Controls the item that is used in place of emeralds in the trade. Must be all caps and offical bukkit names.
#Default EMERALD, examples; EMERALD_BLOCK, DIAMOND, DIAMOND_BLOCK

# cost: Number of the material item needed for the trade.
#Value of 64 by default. Obeys default material stack count.

# book: Changes book needed for the trade to a custom book. Set to 0 for normal book trade.
#Value of 0 by default. Used for making mending trades only possible with create or kit rewards. Use /vmbook to recieve a copy for setup.

# uses:Number of times the trade can be used before the villager restocks.
#Anywhere from 0 for cant trade at all to 9999 for infinite trades. Default 1.
#Villagers will still restock up to 2 times per day.


mending_1:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 64
  book: 0
  uses: 1


# silk_touch: All configs under this heading effect villagers with silk touch trades.

silk_touch_1:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 34
  book: 0
  uses: 1


# fortune_3: All configs under this heading effect villagers with fortune 3 trades.

fortune_3:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 64
  book: 0
  uses: 1


# unbreaking_3: All configs under this heading effect villagers with unbreaking 3 trades.

unbreaking_3:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 64
  book: 0
  uses: 1


# efficiency_5: All configs under this heading effect villagers with efficiency 5 trades.

efficiency_5:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 64
  book: 0
  uses: 1


# efficiency_4: All configs under this heading effect villagers with efficiency 4 trades.

efficiency_4:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 64
  book: 0
  uses: 1


#Example for custom item restriction. Does not have the option for 'book' as most trades are just emeralds.

CLOCK:
  restricted: 0
  change: 0
  material: EMERALD
  cost: 64
  uses: 1